name 'dhoppe-monit'
version '0.0.19'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-monit'
source 'git://github.com/dhoppe/puppet-monit'
summary 'Monit Module'
description 'Monit Module for Debian, Ubuntu'
dependency 'dhoppe/role', '>=0.0.1'
